swagger: "2.0"
info:
    version: "1.0.0"
    title: "Servidor de Licenças de Software"
    license:
        name: "Apache 2.0"
basePath: "/v2"
tags:
  - name: "Licença"
    description: "licença"
schemes:
- "http"
paths:
  /licenca:
    get:
        tags:
        - "Licença"
        summary: "acquire"
        description: "Solicita uma licença para uso durante 1 minuto"
        operationId: "obterLicenca"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
          - name: "usuario"
            in: "query"
            description: "id do usuário"
            required: true
            type: "string"
        responses:
            "200":
                description: retornado
                schema:
                    type: "array"
                    items:
                        $ref: "#/definitions/LicencaSchema"
            "412":
                description: Todos as licenças disponíveis estão sendo utilizadas
                schema:
                    type: "array"
                    items:
                        $ref: "#/definitions/ExceptionSchema"
                        
  /licenca/renovar:
    patch:
        tags:
        - "Licença"
        summary: "renew"
        description: "Renova uma solicitação de licença por mais 1 minuto"
        operationId: "renovarLicenca"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
          - name: "usuario"
            in: "query"
            description: "id do usuário"
            required: true
            type: "string"
          - name: "licenca"
            in: "query"
            description: "id do usuário"
            required: true
            type: "string"  
        responses:
            "204":
                description: Licença disponibilizada com sucesso
                
  /licenca/devolver:
    patch:
        tags:
        - "Licença"
        summary: "release"
        description: "Devolve a licença ao servidor após sua utilização"
        operationId: "devolverLicenca"
        consumes:
        - "application/json"
        produces:
        - "application/json"
        parameters:
          - name: "usuario"
            in: "query"
            description: "id do usuário"
            required: true
            type: "string"
          - name: "licenca"
            in: "query"
            description: "id do usuário"
            required: true
            type: "string" 
        responses:
            "204":
                description: Licença devolvida com sucesso
                          
definitions:
            
  LicencaSchema:
    type: "object"
    properties:
        valor:
            type: string
            example: "DE04D58DC5CCC4B9671C3627FB8D626FE4A15810BC1FE3E724FEEA761965FB71"
  
  ExceptionSchema:
      type: "object"
      properties:
          mensagem:
            type: string
            example: "Não há licença disponível no momento"